version: '3'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./observability/prometheus:/etc/prometheus
      - ./data/prom_data:/prometheus/data
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  postgres_data:
    driver: local
  prom_data:
    driver: local